### ISSUE TITLE
app_card title showing wrong tracker type

### ISSUE THREAD

**Issue by kleinheny** [codeBeamer-Extensions-and-Addons/codebeamer-miro#101]
Hello !
I'm seeing a bug in the app_card title when dealing with multiple tracker types.
For example, I can see app_cards showing "[EPIC|...]" for Retina items in the "PBI (Stories)" tracker or "[PBI|...] for Retina items in the "Features" tracker.
Thanks for your help !

**Comment by urecha** [comment]
Thanks for pointing this out.  
I thought I had fixed it when I noticed it some months ago for the first time. But that bug has apparently crawled back in.  

It now seems to just set one Tracker for all Items that are imported when using the `Import Downstream References` functionality. I think that's just behaviour that we didn't adjust when implementing this, because elsewhise you only can import from one Tracker at a time.

We'll have a look at it.

**Comment by kleinheny** [comment]
Thanks ! You're welcome !
BTW, as I'm a enthusiast user of Retina to Miro integration, I would be happy to try to help you guys, and contribute if I can.
I do have good background as software development (not Typescript, but Javascript and many other languages / frameworks).
Let me know if you believe I could help ...
BR,
Stéphane.
