### ISSUE TITLE
Bug: filter by ID not working when looking for items to import

### ISSUE THREAD

**Issue by C2H6Ethan** [codeBeamer-Extensions-and-Addons/codebeamer-miro#99]

**Comment by urecha** [comment]
@C2H6Ethan Thank you for creating the Github issue regarding the filter not working. To better understand the issue and provide you with the best solution, could you please provide more details?  
It would be helpful if you could describe the expected behavior of the filter and what actual behavior you are currently experiencing. Additionally, if you could include any error messages or screenshots that would also be helpful in diagnosing the issue.  
I would also suggest that you take some time to investigate the behavior of CBQL on this matter independently from our app. This can help you better understand how the filter should work and how to properly use it.  

The more information you can provide, the easier it will be for us to identify the root cause and provide a solution. Thank you!
